/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "storage.h"

#define MAXCHAR 1024

struct Tuple
{
	char* topic;
	char* text;
};

bool_t
init_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval;

	*result = 1;
	
	retval = TRUE;

	/*
	 * insert server code here
	 */

	return retval;
}

bool_t
put_1_svc(char *topic, char *text, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	FILE *fp;

	fp=fopen("storage.txt","w");

	if(fp == NULL)
   	{
      printf("Error!");   
      exit(1);             
   	}

   	fprintf(fp, "%s\n", topic );
   	fprintf(fp, "%s\n", text );
   	*result = 1;

   	// if(fprintf(fp, "%s\n", topic ) < 0 || fprintf(fp, "%s\n", text ) <  0) 
   	// {
   	// 	perror("Can't write to a file");
   	// 	*result = 0;
   	// } else
   	// {
   	// 	*result = 1;
   	// }
   
	fclose(fp);

	/*
	 * insert server code here
	 */
	retval = TRUE;

	return retval;
}

bool_t
get_1_svc(char *topic, char *text, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	char* topicreturn = (char *)malloc(sizeof(char) * 128);
	text = (char *)malloc(sizeof(char) * 1024);
	FILE *fp;
	char str[MAXCHAR];
	fp=fopen("storage.txt","r");
	if (fp==NULL)
	{
		printf("Error!");   
      	exit(1);  
	}
	while (fgets(str, MAXCHAR, fp) != NULL)
	{
        if(strcmp(str,topic))
        {
        	strcpy(topicreturn,str);
        	//strcpy(text_return,str+1);
        }
    } 
   
	//+1 position return
	
	fclose(fp);
	retval = TRUE;
	return retval;
}

int
storage_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
