
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FormatterServiceService", targetNamespace = "http://formatter/", wsdlLocation = "file:/home/mktoun/Documents/UC3M-cours/POSIX_Sockets/FormatterService.wsdl")
public class FormatterServiceService
    extends Service
{

    private final static URL FORMATTERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FORMATTERSERVICESERVICE_EXCEPTION;
    private final static QName FORMATTERSERVICESERVICE_QNAME = new QName("http://formatter/", "FormatterServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/mktoun/Documents/UC3M-cours/POSIX_Sockets/FormatterService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMATTERSERVICESERVICE_WSDL_LOCATION = url;
        FORMATTERSERVICESERVICE_EXCEPTION = e;
    }

    public FormatterServiceService() {
        super(__getWsdlLocation(), FORMATTERSERVICESERVICE_QNAME);
    }

    public FormatterServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMATTERSERVICESERVICE_QNAME, features);
    }

    public FormatterServiceService(URL wsdlLocation) {
        super(wsdlLocation, FORMATTERSERVICESERVICE_QNAME);
    }

    public FormatterServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMATTERSERVICESERVICE_QNAME, features);
    }

    public FormatterServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FormatterServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormatterService
     */
    @WebEndpoint(name = "FormatterServicePort")
    public FormatterService getFormatterServicePort() {
        return super.getPort(new QName("http://formatter/", "FormatterServicePort"), FormatterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormatterService
     */
    @WebEndpoint(name = "FormatterServicePort")
    public FormatterService getFormatterServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://formatter/", "FormatterServicePort"), FormatterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMATTERSERVICESERVICE_EXCEPTION!= null) {
            throw FORMATTERSERVICESERVICE_EXCEPTION;
        }
        return FORMATTERSERVICESERVICE_WSDL_LOCATION;
    }

}
