/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, INIT, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
put_1(char *topic, char *text, int *clnt_res,  CLIENT *clnt)
{
	put_1_argument arg;
	arg.topic = topic;
	arg.text = text;
	return (clnt_call (clnt, PUT, (xdrproc_t) xdr_put_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_1(char *topic, char *text, int *clnt_res,  CLIENT *clnt)
{
	get_1_argument arg;
	arg.topic = topic;
	arg.text = text;
	return (clnt_call (clnt, GET, (xdrproc_t) xdr_get_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
