
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FormatterService", targetNamespace = "http://formatter/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FormatterService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "formatterText", targetNamespace = "http://formatter/", className = "service.FormatterText")
    @ResponseWrapper(localName = "formatterTextResponse", targetNamespace = "http://formatter/", className = "service.FormatterTextResponse")
    @Action(input = "http://formatter/FormatterService/formatterTextRequest", output = "http://formatter/FormatterService/formatterTextResponse")
    public String formatterText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
